### ISSUE TITLE
Can't change camera on iOS

### ISSUE THREAD

**Issue by johnsson-tobias** [OpenVidu/openvidu-call-ionic#2]
Using an iPhoneX, the front camera works, the button to change camera is greyed out.

**Comment by pabloFuente** [comment]
Yes, that's a limitation we found in the plugin OpenVidu is using to support iOS in Ionic platform: https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc

We weren't able to make it working in an easy way, but that doesn't mean it is not possible. We just don't have the time and enough experience with iOS SDK. If you feel like contributing to the project, you could try adding the feature to the plugin.

Regards

**Comment by qjw2bqn** [comment]
@johnsson-tobias which version of you xcode,I can't start successfully.

**Comment by johnsson-tobias** [comment]
Sorry for not replying earlier! I still use 10.1, I have not had time to get my hands on this issue, I can change the camera if I'm running the Ionic project in a regular webpage though. I found this, https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc/issues/72, but I have not investigated if that you be the issue.

**Comment by CSantosM** [comment]
The [cordova-plugin-iosrtc](https://github.com/OpenVidu/cordova-plugin-iosrtc) has been updated to Swift 4.2 and today it is possible to switch the cameras in iOS.

**Comment by ankit0409** [comment]
@CSantosM NOt changing camera from front to back
