### ISSUE TITLE
Voice and video not showing on IOS

### ISSUE THREAD

**Issue by jatins52** [OpenVidu/openvidu-call-ionic#3]
I am able to connect to session and on server side I can see all events related to session on IOS (Iphone 6 and 7 ), application is correctly asking for microphone and camera permissions but voice and video are not transmitting to other device and also not receiving from other side.

It is working correctly on ionic android and web.

I am using openvidu in Ionic 3

can someone please help?

**Comment by phngoctam** [comment]
I have also integrated native iOS code from openvidu-ios-app ’s project GitHub => it’s not display video or audio stream from another peer (android and web) but android or web are all display full of video and audio from iOS. => Issue detail: https://github.com/OpenVidu/openvidu-ios-app/issues/1#issuecomment-548758969

Finally , I have also integrated  ionic Cordova => Same this issue i'm facing. 
Please help me?
Many thanks

**Comment by CSantosM** [comment]
What is your iOS version?

**Comment by phngoctam** [comment]
I have tested with Xcode (Version 10.3 (10G8)) and iPhone 6s (iOS 12.4 (16G77)), iPhone 6s Plus (iOS 12.3.1 (16F203))

**Comment by micaelgallego** [comment]
OpenVidu is supported for ionic 4, not for ionic 3.

Have you tested official tutorial? It is working for you? https://openvidu.io/docs/tutorials/openvidu-ionic/

**Comment by phngoctam** [comment]
i have completed follow step-by-step of https://openvidu.io/docs/tutorials/openvidu-ionic/.

**Comment by gomez34** [comment]
We have the same problem as phngoctam. I can connect with android and web well (android or web screen are all display full of video streams from iOS ) but iOS screen cannot display video streams or any sound from android or web.

**Comment by ankit0409** [comment]
@CSantosM many things is not working in ios

**Comment by crazymxm** [comment]
Same problem in ios13.  It's not work in cordova ,bug works well as web mode in safari of ios.

**Comment by CSantosM** [comment]
Hi, write here all your config configuration and how reproduce the big step by step.

Ionic version
Cordova-iosrtc-version
iPhone version
OpenVidu browser and OpenVidu server version

**Comment by crazymxm** [comment]
@CSantosM 
Ionic version ：5.4.16
Cordova-iosrtc-version ： 6.0.12
iPhone version：IOS 13.2
OpenVidu browser and OpenVidu server version   ：2.12.0

BTW
Works fine in safari ,but not in Cordova app, I think it is the problem of  iosrtc.

**Comment by CSantosM** [comment]
Thanks,
So the problem is Cordova <-> Cordova?

Steps to reproduce it ?

**Comment by crazymxm** [comment]
@CSantosM 
My english is not good.
My test result: 
 Cordova(Iphone) <-> Chrome browser(PC)   :NOT GOOD:    They can't see or hear each other. chat is ok.
 Chrome browser(PC) <->  Chrome browser(PC)    : OK
 Chrome browser(PC) <->  safari(PC)    : OK
I will test more case. thank you.

**Comment by CSantosM** [comment]
Tested with iPhone 7 (13.3) iPhone 7 Plus (13.5.1) and Chrome Browser. 

Every user can hear and see each others. Everything is working as expected.

**Comment by crazymxm** [comment]
Finally I think I found the reason：Turn is not enabled ( Only Sturn enabled by default) in  config of  Kurento  server .

**Comment by Hamik27** [comment]
> Finally I think I found the reason：Turn is not enabled ( Only Sturn enabled by default) in config of Kurento server .

Hello @crazymxm
I new in this topic and i would like to know how could i enable it?

**Comment by micaelgallego** [comment]
@crazymxm do you have an standard OpenVidu deployment? 

Did you need to tweak some default configuration to make app work?

**Comment by crazymxm** [comment]
@Hamik27  @micaelgallego 
In default config of kurento , this line is commented. So, it is  using sturn service only . But sometimes, it's not enough,   so comment out it.

`;turnURL=user:password@127.0.0.1:3478?transport=udp`

(I installed kurento in my ubuntu server by apt get.)
