### ISSUE TITLE
http failure response for https://demos.openvidu.io:4443/api/sessions

### ISSUE THREAD

**Issue by mujahidmasood** [OpenVidu/openvidu-call-ionic#4]
Hello,

While connecting to [https://demos.openvidu.io](url) as in openvidu.service.ts 
I am getting exception 
`There was an error getting the token: undefined Http failure response for https://demos.openvidu.io:4443/api/sessions: 0 Unknown Error`

The only change is I am using capacitor instead of corodova.
It was working few days earlier with same code.

**Comment by pabloFuente** [comment]
Yes, demos OpenVidu deployment has been moved to a different domain name for a few hours to demosopenstack.openvidu.io. Will be back to demos.openvidu.io soon. You can change to the other domain name for now.

Remember that this OpenVidu demos deployment is only for demo/testing purposes and you should change as soon as possible to your own deployment, as it is not secure and anyone can see your video sessions.
