### ISSUE TITLE
Something good to know

### ISSUE THREAD

**Issue by rgustavsson** [OpenVidu/openvidu-call-ionic#6]
Hi!

There's a copyright @2017 label in video-room.page.scss that you may want to get rid of..
I personally thought it was something belonging to some other project so I removed it but then noticed it was needed.

**Comment by micaelgallego** [comment]
Can you describe in more detail what is exactly the issue you are having?

**Comment by rgustavsson** [comment]
I didn't want to spell it out. In your code you have "Copywrite Tokbox". I think you should get rid of that.

**Comment by CSantosM** [comment]
This is because opentok provide a opensource layout in JS and we use it in some of our tutorials
https://github.com/aullman/opentok-layout-js

**Comment by rgustavsson** [comment]
Ah! I see! Still a difference though. You refer to Tokbox, Adam Ullman doesn't do that in his license. But okey, I just wanted to make sure you were aware and it seems you do!
